### ISSUE TITLE
[STYLE] SearchedList 드롭다운 ellipsis, input hover transition 적용

### ISSUE THREAD

**Issue by xxyeon129** [wanted-Team-7/pre-onboarding-10th-4-7#15]
## 📌 Feature Issues
1. 아래 이미지와 같이, SearchedItem의 길이가 길 경우 두줄로 늘어나는 이슈가 있습니다.
<img width="675" alt="스크린샷 2023-05-16 오후 10 56 24" src="https://github.com/wanted-Team-7/pre-onboarding-10th-4-7/assets/102347529/72e1cbce-e51b-4f1f-981b-665aca7a5613">

<br/>

2. input에 hover 시 현재는 border 두께가 바로 변경되는데, transition을 적용해 부드럽게 border 두께가 변화하도록 하고자 합니다.

## ✨ To-do

- [x] SearchedList의 내용이 드롭다운의 너비를 넘을 때 ellipsis 적용
- [x]  transition: border 0.3s 적용
- [x]  SearchedItem click 시 background-color #D5F4F1로 수정

**Comment by minnyoung** [comment]
승연님! 혹시 style 수정 진행하실 때 추가적으로 요청드려도 될까요?
- [ ] SearchedItem click 시 background-color #D5F4F1로 수정

conflict 날 것 같아 요청드려봅니다...!!

**Comment by xxyeon129** [comment]
> @xxyeon129 승연님! style 수정 진행하실 때 한가지 추가적으로 요청드려도 될까요?
> 
> * [ ]  SearchedItem click 시 background-color #D5F4F1로 수정
> 
> conflict 날 것 같아 요청드려봅니다...!!

넵 알겠습니다!

**Comment by Withlaw** [comment]
css로 긴 문장 생략 처리하는 방법 알아갑니다 👏👏👏
